# Generated by Django 4.1.1 on 2022-09-17 13:55

import apps.ResidentManagement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EducAttainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educ_attainment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LastFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_face', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purok_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.CharField(default=apps.ResidentManagement.models.random_string, max_length=5, unique=True)),
                ('firstname', models.CharField(max_length=70)),
                ('middlename', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('suffix', models.CharField(max_length=70)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('single_parent', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('civil_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManagement.civilstatus')),
                ('educ_attainment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManagement.educattainment')),
                ('purok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManagement.purok')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManagement.sex')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManagement.status')),
            ],
        ),
    ]
