# Generated by Django 4.1.1 on 2022-09-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResidentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentsinfo',
            name='years_recided',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
