# Generated by Django 4.1.1 on 2022-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResidentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentsinfo',
            name='phone',
            field=models.CharField(max_length=70),
        ),
    ]
