# Generated by Django 4.1.1 on 2022-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResidentManagement', '0002_alter_civilstatus_id_alter_educattainment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentsinfo',
            name='image',
            field=models.ImageField(upload_to='residents-profile/'),
        ),
    ]
