# Generated by Django 4.1.1 on 2022-09-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResidentManagement', '0002_residentsinfo_years_recided'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residentsinfo',
            old_name='years_recided',
            new_name='years_resided',
        ),
    ]
