# Generated by Django 4.1.1 on 2022-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResidentManagement', '0003_alter_residentsinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentsinfo',
            name='image',
            field=models.ImageField(upload_to='residents-profile'),
        ),
    ]
