# Generated by Django 4.1.1 on 2022-09-22 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ResidentManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_status', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=70)),
                ('date_requested', models.DateField(auto_now=True)),
                ('date_released', models.DateField()),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManagement.residentsinfo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserPortal.documentstatus')),
            ],
        ),
    ]
