# Generated by Django 4.1.1 on 2022-09-23 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ResidentManagement', '0001_initial'),
        ('UserPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidencyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_requested', models.DateField(auto_now=True)),
                ('date_released', models.DateField(null=True)),
                ('purpose', models.CharField(max_length=255)),
                ('res_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ResidentManagement.residentsinfo')),
            ],
        ),
    ]
