# Generated by Django 4.1.1 on 2022-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='age',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
