# Generated by Django 4.1.1 on 2022-09-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0002_residencycertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencycertificate',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserPortal.documentstatus'),
        ),
    ]
