# Generated by Django 4.1.1 on 2022-09-22 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPortal', '0002_clearance_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='res_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
