# Generated by Django 4.1.1 on 2022-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0003_residencycertificate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificateofindigency',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='residencycertificate',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
    ]
