# Generated by Django 4.1.1 on 2022-09-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0004_alter_buildingpermit_date_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='community_tax_date_issued',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clearance',
            name='community_tax_num',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
