# Generated by Django 4.1.1 on 2022-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0004_alter_clearance_res_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='date_released',
            field=models.DateField(null=True),
        ),
    ]
