# Generated by Django 4.1.1 on 2022-09-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0005_alter_clearance_date_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UserPortal.documentstatus'),
        ),
    ]
