# Generated by Django 4.1.1 on 2022-10-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0006_clearance_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpermit',
            name='document_type',
            field=models.CharField(default='Building Permit', max_length=70),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='document_type',
            field=models.CharField(default='Business Permit', max_length=70),
        ),
        migrations.AddField(
            model_name='certificateofindigency',
            name='document_type',
            field=models.CharField(default='Certificate of Indigency', max_length=70),
        ),
        migrations.AddField(
            model_name='residencycertificate',
            name='document_type',
            field=models.CharField(default='Certificate of Residency', max_length=70),
        ),
    ]
