# Generated by Django 4.1.1 on 2022-09-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResidentManagement', '0003_rename_years_recided_residentsinfo_years_resided'),
        ('UserPortal', '0007_alter_clearance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='res_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ResidentManagement.residentsinfo'),
        ),
    ]
