# Generated by Django 4.1.1 on 2022-09-22 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPortal', '0009_alter_clearance_res_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='res_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserPortal.documentstatus'),
        ),
    ]
