# Generated by Django 4.1.1 on 2022-09-22 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPortal', '0010_alter_clearance_res_id_alter_clearance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='res_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
