# Generated by Django 4.1.1 on 2022-09-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0012_alter_clearance_res_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='age',
            field=models.CharField(max_length=70),
        ),
    ]
