# Generated by Django 4.1.1 on 2022-09-22 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserPortal', '0013_alter_clearance_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
