# Generated by Django 4.1.1 on 2022-10-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementManagement', '0002_alter_announcement_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
