# Generated by Django 4.1.1 on 2022-10-02 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementManagement', '0004_alter_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
