# Generated by Django 4.1.1 on 2022-10-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementManagement', '0005_announcement_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(upload_to='announcement-Images'),
        ),
    ]
